/* Auto-generated by @napi-rs/cli — keep in sync with src/lib.rs by hand
 * until the P3.2 build pipeline regenerates this from cargo metadata. */

/** Schema version supported by this engine (mirrors CURRENT_SCHEMA_VERSION). */
export function schemaVersionSync(): number

/** Stable engine identifier — should equal the string `"genesis-block"`. */
export function engineNameSync(): string
